name = "discussion-kit-oauth"
main = "worker.js"
compatibility_date = "2025-01-01"

[vars]
# Comma-separated list of origins allowed to use this proxy
ALLOWED_ORIGINS = "https://patch-com.github.io"

# Your GitHub OAuth app's client id
GITHUB_CLIENT_ID = "Ov23liJ0jnfnjBfcRrGo"
